# 
#  (C) by Remo Dentato (rdentato@gmail.com)
# 
# This sofwtare is distributed under the terms of the BSD license:
#   http://creativecommons.org/licenses/BSD/
#   http://opensource.org/licenses/bsd-license.php
#


release:
	cd abcdump; make release
	cd nousym; make release
	cd crdlyr; make release

debug:
	cd abcdump; make debug
	cd nousym; make debug
	cd crdlyr; make debug

clean:
	cd abcdump; make clean
	cd nousym; make clean
	cd crdlyr; make clean
